run:
  timeout: 5m

linters:
  disable:
    - typecheck  # Disabled - version compatibility issues
    - errcheck   # Disabled - too strict for codebase, critical issues resolved in manual audit
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic

linters-settings:
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - nilfunc
      - printf
  gosec:
    excludes:
      - G101  # Hard coded credentials (documented test values)
      - G104  # Errors unhandled (covered by comprehensive audit, errcheck disabled)
      - G115  # Integer overflow conversion (false positives)
      - G201  # SQL string formatting (parameterized queries, safe usage)
      - G204  # Subprocess launched with variable (intentional for generator/compiler)
      - G301  # Directory permissions 0755 (intentional for generated code)
      - G304  # File path provided as taint input (required for SDK generator)
      - G306  # Poor file permissions (we intentionally use 0644 for PID files)
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .claude
    - examples
    - scripts
    - sdk

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
    # Exclude generated code
    - path: _gen\.go
      linters:
        - all
