run:
  timeout: 5m

linters:
  disable:
    - typecheck  # Disabled - version compatibility issues
    - errcheck   # Disabled - too strict for codebase, critical issues resolved in manual audit
    - unused     # Disabled - many work-in-progress provider implementations
    - gocritic   # Disabled - mostly style preferences, not critical issues
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - nilfunc
      - printf
  gosec:
    excludes:
      - G101  # Hard coded credentials (documented test values)
      - G104  # Errors unhandled (covered by comprehensive audit, errcheck disabled)
      - G112  # Potential Slowloris Attack (ReadHeaderTimeout - internal service)
      - G114  # HTTP serve without timeout (internal admin API)
      - G115  # Integer overflow conversion (false positives)
      - G201  # SQL string formatting (parameterized queries, safe usage)
      - G204  # Subprocess launched with variable (intentional for generator/compiler)
      - G301  # Directory permissions 0755 (intentional for generated code)
      - G302  # File permissions 0644 (intentional for daemon PID files)
      - G304  # File path provided as taint input (required for SDK generator)
      - G306  # Poor file permissions (intentional for PID files)
      - G401  # Weak crypto primitive (SHA1 for WebSocket per RFC 6455)
      - G404  # Weak random (math/rand for non-crypto use)
      - G505  # Blocklisted SHA1 (required for WebSocket protocol)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .claude
    - examples
    - scripts
    - sdk

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
    # Exclude generated code
    - path: _gen\.go
      linters:
        - all
