package generator

import (
	"text/template"
)

// Templates holds code generation templates
type Templates struct {
	OpenAICompatible    *template.Template
	AnthropicCompatible *template.Template
	Custom              *template.Template
}

// LoadTemplates loads all code generation templates
func LoadTemplates() (*Templates, error) {
	openaiTmpl, err := template.New("openai").Parse(openaiCompatibleTemplate)
	if err != nil {
		return nil, err
	}

	anthropicTmpl, err := template.New("anthropic").Parse(anthropicCompatibleTemplate)
	if err != nil {
		return nil, err
	}

	customTmpl, err := template.New("custom").Parse(customRESTTemplate)
	if err != nil {
		return nil, err
	}

	return &Templates{
		OpenAICompatible:    openaiTmpl,
		AnthropicCompatible: anthropicTmpl,
		Custom:              customTmpl,
	}, nil
}

// openaiCompatibleTemplate generates OpenAI-compatible providers
const openaiCompatibleTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// {{.ProviderName}}Provider implements OpenAI-compatible API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// ChatCompletion sends a chat completion request
func (p *{{.ProviderName}}Provider) ChatCompletion(ctx context.Context, req interface{}) (interface{}, error) {
	url := strings.TrimRight(p.baseURL, "/") + "/v1/chat/completions"

	jsonData, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API error (status %d): %s", resp.StatusCode, string(body))
	}

	var result map[string]interface{}
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("failed to parse response: %w", err)
	}

	return result, nil
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}
`

// anthropicCompatibleTemplate generates Anthropic-compatible providers
const anthropicCompatibleTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// {{.ProviderName}}Provider implements Anthropic-compatible API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// CreateMessage sends a message request (Anthropic-style)
func (p *{{.ProviderName}}Provider) CreateMessage(ctx context.Context, req interface{}) (interface{}, error) {
	url := strings.TrimRight(p.baseURL, "/") + "/v1/messages"

	jsonData, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("x-api-key", p.apiKey)
	httpReq.Header.Set("anthropic-version", "2023-06-01")

	resp, err := p.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API error (status %d): %s", resp.StatusCode, string(body))
	}

	var result map[string]interface{}
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("failed to parse response: %w", err)
	}

	return result, nil
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}
`

// customRESTTemplate generates custom REST API providers
const customRESTTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// {{.ProviderName}}Provider implements custom REST API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// Request sends a generic request to the provider
func (p *{{.ProviderName}}Provider) Request(ctx context.Context, endpoint string, payload interface{}) (interface{}, error) {
	url := strings.TrimRight(p.baseURL, "/") + endpoint

	var httpReq *http.Request
	var err error

	if payload != nil {
		jsonData, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal payload: %w", err)
		}

		httpReq, err = http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(jsonData))
		if err != nil {
			return nil, fmt.Errorf("failed to create request: %w", err)
		}

		httpReq.Header.Set("Content-Type", "application/json")
	} else {
		httpReq, err = http.NewRequestWithContext(ctx, "GET", url, nil)
		if err != nil {
			return nil, fmt.Errorf("failed to create request: %w", err)
		}
	}

	httpReq.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("API error (status %d): %s", resp.StatusCode, string(body))
	}

	var result map[string]interface{}
	if err := json.Unmarshal(body, &result); err != nil {
		// If not JSON, return raw string
		return string(body), nil
	}

	return result, nil
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}

// Available endpoints:
{{- range .Endpoints}}
// - {{.Method}} {{.Path}} ({{.Purpose}})
{{- end}}
`
