package generator

import (
	"text/template"
)

// Templates holds code generation templates
type Templates struct {
	OpenAICompatible    *template.Template
	AnthropicCompatible *template.Template
	Custom              *template.Template
}

// LoadTemplates loads all code generation templates
func LoadTemplates() (*Templates, error) {
	openaiTmpl, err := template.New("openai").Parse(openaiCompatibleTemplate)
	if err != nil {
		return nil, err
	}

	anthropicTmpl, err := template.New("anthropic").Parse(anthropicCompatibleTemplate)
	if err != nil {
		return nil, err
	}

	customTmpl, err := template.New("custom").Parse(customRESTTemplate)
	if err != nil {
		return nil, err
	}

	return &Templates{
		OpenAICompatible:    openaiTmpl,
		AnthropicCompatible: anthropicTmpl,
		Custom:              customTmpl,
	}, nil
}

// openaiCompatibleTemplate generates OpenAI-compatible providers
const openaiCompatibleTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"context"
	"fmt"
	"net/http"
)

// {{.ProviderName}}Provider implements OpenAI-compatible API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// ChatCompletion sends a chat completion request
func (p *{{.ProviderName}}Provider) ChatCompletion(ctx context.Context, req interface{}) (interface{}, error) {
	// TODO: Implement OpenAI-compatible chat completion
	return nil, fmt.Errorf("not implemented")
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}
`

// anthropicCompatibleTemplate generates Anthropic-compatible providers
const anthropicCompatibleTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"context"
	"fmt"
	"net/http"
)

// {{.ProviderName}}Provider implements Anthropic-compatible API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// CreateMessage sends a message request (Anthropic-style)
func (p *{{.ProviderName}}Provider) CreateMessage(ctx context.Context, req interface{}) (interface{}, error) {
	// TODO: Implement Anthropic-compatible message creation
	return nil, fmt.Errorf("not implemented")
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}
`

// customRESTTemplate generates custom REST API providers
const customRESTTemplate = `// Code generated by modelscan; DO NOT EDIT.
package generated

import (
	"context"
	"fmt"
	"net/http"
)

// {{.ProviderName}}Provider implements custom REST API for {{.ProviderName}}
type {{.ProviderName}}Provider struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
}

// New{{.ProviderName}}Provider creates a new {{.ProviderName}} provider
func New{{.ProviderName}}Provider(apiKey string) *{{.ProviderName}}Provider {
	return &{{.ProviderName}}Provider{
		apiKey:     apiKey,
		baseURL:    "{{.BaseURL}}",
		httpClient: &http.Client{},
	}
}

// GetBaseURL returns the base URL
func (p *{{.ProviderName}}Provider) GetBaseURL() string {
	return p.baseURL
}

// Request sends a generic request to the provider
func (p *{{.ProviderName}}Provider) Request(ctx context.Context, endpoint string, payload interface{}) (interface{}, error) {
	// TODO: Implement custom REST API request
	return nil, fmt.Errorf("not implemented")
}

// ListModels lists available models
func (p *{{.ProviderName}}Provider) ListModels(ctx context.Context) ([]string, error) {
	models := []string{
{{- range .Models}}
		"{{.ID}}",
{{- end}}
	}
	return models, nil
}

// Available endpoints:
{{- range .Endpoints}}
// - {{.Method}} {{.Path}} ({{.Purpose}})
{{- end}}
`
